package client;

import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 * The ConfirmFrame class inheriting the JFrame displays an invitation from other player
 */
@SuppressWarnings("serial")
public class ConfirmFrame extends javax.swing.JFrame {
	private String name = null;
	private ListenServer listenServer;
	/**
     * Creates new form ConfirmFrame
	 * @param listenServer ListenServer
	 * @param name The competitor's name
     */
    public ConfirmFrame(ListenServer listenServer,String name) {
    	this.listenServer = listenServer;
    	this.name = name;
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText( name +" muon choi game voi ban.");

        jLabel2.setText("Chap nhan loi moi?");

        jButton1.setText("    OK    ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    /**
	* The method handling event player disagree and click Cancel button
	*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	try {
    		//System.out.println(name);
			listenServer.SendMessage(6, null);
		} catch (IOException e) {
			e.printStackTrace();
		}
    	this.dispose();
    }                                        
    
    /**
     * The method handling event player agree and click OK button
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	try {
			listenServer.SendMessage(6, name);
		} catch (IOException e) {
			e.printStackTrace();
		}
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaroFrame(listenServer,true,true, name).setVisible(true);
            }
        });
    	this.dispose();
    }                                        

    
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   
}
